project_id = "egmhythtnroyyiicuikv"

[functions.generate-labour-summary]
verify_jwt = false

[functions.validate-quote]
verify_jwt = false

[functions.send-client-link]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.generate-invoice-token]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false
